name: Checkov
on: 
  pull_request:
  push:

jobs: 
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.6]
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v1
        with: 
          python-version: $ 
      - name: Test with Checkov
        run: | 
          pip install checkov
          checkov -d . --external-checks-git https://github.com/nmr-sso-org-2/nmr-checkov-v1.git//my_extra_checks

